Colors = {
	UEF = 'FF009CFF',
	AEON = 'FF53BC00',
	CYBRAN = 'FFFF4040',
	SERAPHIM = 'FFFFBF00',
	NOMADS = 'FFFF7200',
	CYAN = 'ff70ffff',
	PURPLE = 'ffff70ff',
	WHITE = 'ffffffff',
	GOLD = 'ffffffaa',
	GREY_LIGHT = 'ffC0C0C0',
	GREY_MEDIUM = 'ff777777',
	GREY_DARK = 'ff404040',
	BLUE1 = "ff436eee",      -- new blue1
    RED1 = "FFe80a0a",      -- Cybran red
    GREY1 = "ff616d7e",      -- grey
    YELLOW1 = "fffafa00",      -- new yellow
    ORANGE = "FFFF873E",      -- Nomads orange
    PURPLE2 = "ff9161ff",      -- purple
    PINK = "ffff88ff",      -- pink
    GREEN1 = "ff2e8b57",      -- new green
    BLUE2 = "FF2929e1",      -- UEF blue
    PURPLE_DARK = "FF5F01A7",      -- dark purple
    FUSHIA = "ffff32ff",      -- new fuschia
    ORANGE_LIGHT = "ffffbf80",      -- lt orange
    SERA_GOLDEN = "ffa79602",      -- Sera golden
    BROWN = "ffb76518",      -- new brown
    RED_DARK = "ff901427",      -- dark red
    OLIVE = "FF2F4F4F",      -- olive (dark green)
    GREEN_MEDIUM = "ff40bf40",      -- mid green
    AQUA = "ff66ffcc",      -- aqua
    GREEN_ORDER = "ff9fd802",      -- Order Green
}
